### ISSUE TITLE
Update Course: C777

### ISSUE THREAD

**Issue by Ktanaqui** [Huusky/bubo#11]
update course C777 in DB.

**Name**: Web Development Applications

**Description**: This course prepares students for the CIW Advanced HTML5 and CSS3 Specialist certification exam.

This course builds upon a student's manual coding skills by teaching how to develop web documents and pages using the Web Development Trifecta: HTML5 (Hypertext Markup Language version 5) and CSS3 (Cascading Style Sheets version 3) and JavaScript. Students will utilize the skills learned in this course to create web documents and pages that easily adapt to display on both traditional and mobile devices. In addition, students will learn techniques for code validation and testing, form creation, inline form field validation, and mobile design for browsers and apps, including Responsive Web Design (RWD).

*note that this course is already in the db but missing a description, so I edited the template a tiny bit.

**Comment by Huusky** [comment]
Updated in DB. Closing.
