### ISSUE TITLE
Bubo - New BS BA ITM Course map

### ISSUE THREAD

**Issue by idlerig** [Huusky/bubo#2]
[Bubo - New BS BA ITM Course map.xlsx](https://github.com/Huusky/bubo/files/4179234/Bubo.-.New.BS.BA.ITM.Course.map.xlsx)

This spreadsheet has the course name-course number mappings for both the Pre March 1, 2020 program, titled: _Bachelor of Science, Business - Information Technology Management._ After March 1, the program will be called _Bachelor of Science Business Administration Information Technology Management_. About half of the courses will change. These are listed in a separate tab.
 
-- 21 courses appear to have the same title and course material. I moved the course number over in the table, but I'm not 100% sure that's accurate for the new courses.

-- 19 courses are new, but have similar names to the old program. 

-- 5 will be dropped, with no similar title in the new program of study.

The credit count is accurate for all programs, both past and future.

WGU Program Description Page (reflects Mar 1 curriculum)
https://www.wgu.edu/online-business-degrees/it-information-technology-management-bachelors-program.html

Actual (new) Program Guide
[BSBAIT.pdf](https://github.com/Huusky/bubo/files/4179240/BSBAIT.pdf)

https://www.wgu.edu/content/dam/western-governors/documents/programguides/2017-guides/business/BSBAIT.pdf

Old Program Guide
[Pgm Guide - Old - Business - Information Technology Management.pdf](https://github.com/Huusky/bubo/files/4179252/Pgm.Guide.-.Old.-.Business.-.Information.Technology.Management.pdf)

**Comment by Huusky** [comment]
All courses added/updated in DB. Closing.
