### ISSUE TITLE
Graduated announcement

### ISSUE THREAD

**Issue by Ktanaqui** [Huusky/bubo#42]
**Is your feature request related to a problem? Please describe.**
Nein~

**Describe the solution you'd like**
command: graduated user degree
posts in #announcements a simple message - "User graduated with degree! Smother them with congratulations!" or something

**Describe alternatives you've considered**
nein

**Additional context**
n/a

**Comment by Huusky** [comment]
Will not implement. Too many announcements might make people mute the channel.
