### ISSUE TITLE
Add Course: MGT2

### ISSUE THREAD

**Issue by c0deweaver** [Huusky/bubo#45]
Add course MGT2 to DB.

**Name**: IT Project Management

**Description**: [DESCRIPTION]

from discord: https://discord.com/channels/600152872767979523/600153846907666432/833924170634625055

**Comment by Huusky** [comment]
INSERT INTO `bubo-prd`.`course` (`id`, `name`) VALUES ('MGT2', 'IT Project Management');

Added. Closing.
