### ISSUE TITLE
Update Course: C993

### ISSUE THREAD

**Issue by Ktanaqui** [Huusky/bubo#8]
Update course C993 in DB.

**Name**: Structured Query Language

**Description**: This course prepares the student for the Oracle Database SQL (1Z0-071) certification exam. Students will master the SQL language that will allow them to restrict and sort data; create schema objects; control user access; and manage data, objects, and tables.

*note that this course is already in the db but missing a description, so I edited the template a tiny bit.

**Comment by Huusky** [comment]
Updated in DB. Closing.
